BINARY_NAME = $(notdir $(CURDIR))
CFLAGS = -std=c++11
INCLUDES = 


SRC = $(wildcard *.cpp)
NOM = $(basename $(notdir $(SRC)))
OBJ = $(addsuffix .o, $(NOM))

all: $(BINARY_NAME)

rebuild: remake

remake: clean $(BINARY_NAME)

$(BINARY_NAME): $(OBJ)
	g++ $(CFLAGS) $(OBJ) -o $(BINARY_NAME)

# Build all the .o files
%.o: %.cpp
	g++ $(CFLAGS) -c $< $(INCLUDES) -o $@
	
# Remove all files generated by compilation (executables included)
clean:
	rm -f $(BINARY_NAME) *.o *.gch

# Remove all files generated by compilation (except executables)
clear:
	rm -f *.o *.gch